export default {
    products: [
        {
            _id: '1',
            name: "Olive Oil Styling Gel",
            category: 'Gel',
            image: '/images/eco.jpg',
            price: 3,
            brand: 'Eco Style',
            rating: 4.5,
            numReviews: 7,
            description: 'This is the description',
            inventory: 6,
        },
        {
            _id: '2',
            name: "Curl Enhancing Smoothie",
            category: 'Gel',
            image: '/images/shea.jpg',
            price: 2,
            brand: 'Shea Moisture',
            rating: 5,
            numReviews: 8,
            inventory: 3,
        },
        {
            _id: '3',
            name: "Olive Oil Scalp Oil",
            category: 'Gel',
            image: '/images/olive.jpg',
            price: 4,
            brand: 'ORS',
            rating: 4,
            numReviews: 6,
            inventory: 0,
        },
        {
            _id: '4',
            name: "Detangling Comb",
            category: 'combs',
            image: '/images/comb.jpg',
            price: 2,
            brand: 'Beauty Supply',
            rating: 3.5,
            numReviews: 5,
            inventory: 9,
        },
    ]
}